## CONFIGURAÇÕES TESTES/DESENVOLVIMENTO

message: Configurações ativas para TESTES/DESENVOLVIMENTO

server:
   port: 8081
   servlet:
      context-path: /
   undertow:
      accesslog:
         prefix: '[CINECLUBE-APP]'

spring:
   application:
      name: backend
   jpa:
      show_sql: false
      format_sql: true
      hibernate:
         ddl-auto: update
         naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
         hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            temp:
               use_jdbc_metadata_defaults: false
   servlet:
      multipart:
         max-file-size: -1
         max-request-size: -1
   jmx:
      enabled: false
   datasource:
      url: jdbc:postgresql://localhost:5432/cineclube_app
      username: postgres
      password: postgres
   output:
      ansi:
         enabled: DETECT

#ACTUATOR
management:
   endpoint:
      health:
         show-details: always
   endpoints:
      web:
         exposure:
            include: '*'

info:
   app:
      name: '@project.name@'
      description: '@project.description@'
      version: '@project.version@'
      encoding: '@project.build.sourceEncoding@'
      java:
         version: '@java.version@'

jwt:
   header: 'Authorization'
   secret: pgo-2020-app
   enable: true

logging:
   level:
      root: ERROR
      org.springframework: ERROR
      springfox.documentation.spring: ERROR
      br.com.cineclub.*: DEBUG
      org.hibernate: ERROR
   file:
      name: 'logs/cineclube_app.log'
      max-size: 5 Mb
      rolling-file-name: "old/%d{yyyy-MM-dd}/"
   pattern:
      console: '%d{dd-MM-yyyy HH:mm:ss} | %logger{0}:%L [ %-5level ]  :  %msg%n'
      file: '%d{dd-MM-yyyy HH:mm:ss} | %logger{0}:%L [ %-5level ]  :  %msg%n'